### ISSUE TITLE
Cleaning errors in Xubuntu 16.04

### ISSUE THREAD

**Issue by stucka** [ilikenwf/apt-fast#100]
Using apt-fast to fetch files results in a folder that neither
apt-fast clean
apt-get clean

can actually clean. ("Problem unlinking the file apt-fast - Clean (21: Is a directory)

My 16.04 virtual machine is fully updated; I think this is now the final beta.

**Comment by Burnfaker** [comment]
i don't know what you mean

**Comment by stucka** [comment]
apt-fast downloads to /var/cache/apt/archives/apt-fast
the apt-get with Xubuntu 16.04 (presumably the same one was the Ubuntu apt-get) is now unable to kill off that directory and clean it. "apt-fast clean" I think is calling "apt-get clean" so apt-fast can't even clean up itself. 

One partial solution would presumably be to have "apt-fast clean" run "rm -rf /var/cache/apt/archives/apt-fast"   and then call "apt-get clean" to finish up. That won't take care of problems where someone's using "apt-get clean" and wants to purge files downloaded with apt-fast.

**Comment by rcspam** [comment]
@stucka 
To prevent display this error, you can remove "/var/cache/apt/archives/apt-fast/" directory and  change the DLDIR variable in /etc/apt-fast.conf to another path (i.e. /var/cache/my_apt-fast/archives/apt-fast).

**Comment by Tecktron** [comment]
```
$ apt-fast clean
W: Problem unlinking the file apt-fast - Clean (21: Is a directory)
```

This has showed up for me since I upgraded to Ubuntu 16.04 this weekend (I'm not an instant upgrader, like to give it a couple of months). After finding this post and reading though the `/etc/apt-fast.conf file`, I set this to the _standard_ setting listed in the comments and all is now working fine, though I am concerned about the cleanup of that directory since it's not going to be presumably emptied by `apt-clean` anymore.

Seeing as how this will become be an ongoing issue moving forward with further releases of Ubuntu (unless they change apt), is there a better way for this to be fixed without the user having to adjust the conf file? 

I agree with @stucka, the idea of having apt-fast cleanup that directory after itself (wherever the conf says it is) does seem like a solution (programs should always cleanup after themselves). However, also setting the to default to the _standard_ directory (or something else) so that it doesn't interfere with standard `apt` operations should also be considered.

Thanks

**Comment by annat83** [comment]
Hello, there is a solution to this issue on Ubuntu 16.04 Unity?

**Comment by stucka** [comment]
@annat83 : Looks like the fix was implemented in September. I'm guessing you've upgraded an older system?

In your apt-fast.conf file, I think you're looking for
DLDIR=/var/cache/apt-fast

And you may have to manually remove everything in your /var/cache/apt folder first. Don't delete the wrong folder.

**Comment by annat83** [comment]
@stucka So maybe deleting and reinstalling sure fix it then right?

**Comment by stucka** [comment]
@annat83 , I don't know when you installed it or how you installed it or even which Linux variant you're running it on. 

My guess is you can
sudo nano /etc/apt-fast.conf          and add that line

Or possibly something like:
sudo add-apt-repository ppa:saiarcot895/myppa
sudo apt-get update
sudo apt-get -y install --reinstall apt-fast

**Comment by Lasall** [comment]
apt-fast 1.8.5-1 on the apt-fast/stable PPA should fix this issue. Please reopen if it still persists. Thank you for reporting and helping with workarounds!
