### ISSUE TITLE
no apt repository for apt-fast package for disco/debian/kali

### ISSUE THREAD

**Issue by jayenashar** [ilikenwf/apt-fast#156]
Using the first installation method, I'm getting this error:

```
W: The repository 'http://ppa.launchpad.net/apt-fast/stable/ubuntu disco Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/apt-fast/stable/ubuntu/dists/disco/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

which I believe is because there are no PPA for debian, so it's trying to masquerade as ubuntu disco (which also doesn't have a PPA).  manually changing to bionic gives this warning:

```
W: GPG error: http://ppa.launchpad.net/apt-fast/stable/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1EE2FF37CA8DA16B
W: The repository 'http://ppa.launchpad.net/apt-fast/stable/ubuntu bionic InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

but at least i can now install apt-fast.

```
Distributor ID: Debian
Description:    Debian GNU/Linux 9.7 (stretch)
Release:        9.7
Codename:       stretch
```

**Comment by MycroftHolmes1989** [comment]
Same for Kali Linux. It should work well with Kali, but there's no ppa for Kali.

**Comment by guekho64** [comment]
<h1> Why?! </h1>

These kind of situations happen because, in theory, `PPA's` were made with Ubuntu in mind, not 
Debian, _**but**_, due to the fact that both use `apt` (`dpkg`) as their package manager, people though that `PPA's` would work in both distributions, and they weren't wrong: Actually, `PPA's` work both in Ubuntu & Debian (And practically any distro using `apt & dpkg`)...but there's a problem:

As `PPA's` were designed originally to be used by Ubuntu, these repositories _only_ contain packages for Ubuntu, thus the repository packages are named, ordered and indexed after an `Ubuntu Codename`, so that's why these errors arise, because Debian names differ a lot from the ones used by Ubuntu, and, when the `PPA` tries to find the codename "Stretch", it'll realize that it doesn't exist, falling back to the most recent distro available (In Ubuntu) -> "Disco" (2019)

<I>Interestingly, Debian **DOES NOT** have the `apt-add-repository` command by default (That's what I remember. Maybe Debian now ships that command by default?), so you must install a certain package to obtain the command:</i>

* Debian 8 -> `software-properties-common`
* Debian 7 -> `python-software-properties` (At least package version 0.75. Earlier versions won't work)

<h2> How to solve it? </h2>

As @jayenashar pointed out, the "easy" way to solve this problem quickly is to modify the file created by `apt-add-repository` located in `/etc/apt/sources.list.d/`. <i>The name of the file will vary depending on the name of the `PPA` that was added.</i>

<b> In this specific case, it appears that adding <i>apt-fast</i>'s repo creates a file named "apt-fast-stable-<i>{Ubuntu Codename}</i>.list"</b>

You just need to open it (With superuser rights) and replace any `Ubuntu Codenames` you find in the file with the <i>nearest</i> Ubuntu version codename to your Debian version. For example:

Debian 7 (Wheezy) -> Ubuntu <i>Precise/Trusty</i>
Debian 8 (Jessie) -> Ubuntu <i>Trusty/Xenial</i>
Debian 9 (Stretch) -> Ubuntu <i>Xenial/Bionic</i>

Those are the codenames I used to edit my files back when I used Debian. The <I>slash</i> indicates that you could technically use any of the mentioned codenames, depending if the `PPA` you're trying to install supports only one of them. If both are available, try first using the most recent one.

<details><summary>Example</summary>
<br>

_From:_

deb http://ppa.launchpad.net/apt-fast/stable/ubuntu **disco** main
deb-src http://ppa.launchpad.net/apt-fast/stable/ubuntu **disco** main

_To:_ (Debian 8)

deb http://ppa.launchpad.net/apt-fast/stable/ubuntu **xenial** main
deb-src http://ppa.launchpad.net/apt-fast/stable/ubuntu **xenial** main

</br>
</details>

<h3> There are other ways to solve this... </h3>

...although you might mess your Debian installation if you attempt to apply this fix...

If you get an error like:` W: GPG error: http://ppa.launchpad.net/apt-fast/stable/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY` **1EE2FF37CA8DA16**

You should try executing this command first: `sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys KEY_ID`, where `KEY_ID` it's the missing key

If that doesn't work, you might need to modify the system in such a way that the command `lsb_release` report a different distro, version, name, and description, so `apt-add-repository` will automatically add every new `PPA` with the codename reported by `lsb_release` (Years ago I did this, and I definitively don't recommend doing this, except you really must do it. If that's the case, a backup of the original files should be mandatory...

I don't recall the exact way to do this, but I'm pretty sure it's very simple, maybe too much...

<h4> Nowadays... </h4>

...there are some special repositories made exclusively for Debian, though they aren't hosted  in `Launchpad` as normal `PPA's` do, but they work as expected.

I don't know many of them, but If I recall correctly, the package `neofetch` has a dedicated repository hosted in <i>Dropbox</i> and accepts Debian distros without any kind of hassle.

<h5> And... </h5>

...rolling release distros, like `Kali Linux` should apply this method using the most recent Ubuntu version, in this case, <i>disco</i>

**Comment by jayenashar** [comment]
somehow i have `software-properties-common` already, looks like `software-properties-kde` depends on it, but i have neither `apper` nor `plasma-discover` so i don't know why i installed this.

should we create a separate issue for "no PPA for disco"?

**Comment by guekho64** [comment]
@jayenashar I'm not very familiar with the `KDE Desktop` nor with any of its components, but based on my knowledge and past experiences with Ubuntu, I'd say that installing any `KDE` app on a non-KDE (or non-Qt) desktop would bring a lot of dependencies that, most of the time, aren't necessary, and could cause problems with other libraries that might be already installed.

I'd recommend doing a `sudo apt-get --purge autoremove <package>` to attempt a complete removal of those packages, whether you're trying to optimize your disk space, or if any of those packages are causing trouble. If neither of those are happening, maybe the best would be to leave the system as it is alredy (<i>If ain't broken, don't fix it...</i>)

<hr>

Back to the main topic, I'd say that renaming this issue would suffice to avoid confusion related to Debian & Ubuntu `PPA's`, but if you prefer to open a completely new issue (And close this one as well), I'm not complaining!

(Is it possible to rename an issue? I can't recall if that was possible, although I'm almost sure it is...)

**Comment by jayenashar** [comment]
`autoremove` only works on packages that have been automatically installed.  `software-properties-kde` is marked as manually installed.

this install of debian is 12 years old.  i've gotten pretty good at breaking and fixing things with it.

<hr>

i can edit it, as the author, not sure if anyone can.

**Comment by guekho64** [comment]
I though that you'd rename the issue swapping "debian" for "disco", but you just added "Disco" and "Kali" instead, ha!

In theory, any kind of file system (With support for directories) can host a `PPA`, with support for any kind of distro that you want, even if you decide to not follow the naming rules from Ubuntu or Debian, or any other kind of naming conventions.

In fact, repositories aren't anything else than just a bunch of <i>ordered</i> directories with a couple of files needed for `apt` to recognize that directory tree as a `PPA`, meaning that <i>almost</i> anything possible with a directory should also be possible with a `PPA`.

That being said: Including support for <i>Debian</i> or <i>Kali Linux</i> in a `PPA` by default is 100% possible, <b>but</b> the "<i>problem</i>" here is the platform where the `PPA` is hosted: `Launchpad`

As far as I know, `Launchpad` (Just like `PPA's`) was created specifically to be used by Ubuntu users, and I've never seen a `PPA` hosted in `Launchpad` being able to support <i>Debian</i>...

I can't recall where I read about this (It's been a long time since then...), but I think that `PPA` owners don't have complete control over their own `PPA`, as `Launchpad` automatically manages all the setup stuff for you, and because of the nature of `Launchpad` itself, obviously it'll only create entries for <i>Ubuntu</i>, because it's main purpose is to serve packages to Ubuntu and no one else...

I can't confirm the above information because I don't own a `PPA`, but If things have changed nowadays, that'd be great!

Another option would be to create a secondary repository (Outside of `Launchpad`), just like `neofetch` did, and add support for <i>Debian</i> (And other distros) in that `PPA`, without having to modify the actual `PPA` structure and/or deleting it.

**Comment by jayenashar** [comment]
ok, i tried again

**Comment by Lasall** [comment]
Thanks a lot for your detailed instructions @guekho64 .

apt-fast is just a shell script. Meaning as long as bash is supported, then apt-fast will work, no matter the Debian-flavored distribution or version (and as long as there is no alias f*up). I can update the Readme with the instructions guekho64 gave above, namely to use the PPA as is and just explicitly use an Ubuntu codename.

**Comment by Lasall** [comment]
I update the installation instructions in the Readme. Please feel free to ask any open questions.
