### ISSUE TITLE
Add Hirsute target for Ubuntu PPA

### ISSUE THREAD

**Issue by moritzheiber** [ilikenwf/apt-fast#193]
I know, it's only been two days, but the [Ubuntu PPA](https://launchpad.net/~apt-fast/+archive/ubuntu/stable) is missing a `hirsute` target :wink: 

I'd love to have support for `apt-fast` for 21.04 "Hirsute Hippo" through the Ubuntu PPA.

Appreciate your work on this fantastic tool, thank you! :heart:

**Comment by Lasall** [comment]
Thank you for reporting this issue.

I updated all available versions in the PPA. I had a little trouble with 21.04 because the 21.10 version (which built as well) is still using 21.04 tags. This might recult in a race condition whichever source package builds first. Therefore the 21.04 binary is a copy of the 20.10 binary now. This should be ok since apt-fast is a script and doesn't link against other libraries. I didn't verify the versions of the dynamic dependencies (misc:Depends) yet.

**Comment by Lasall** [comment]
Automatic deps verified (debconf (>= 0.5) | debconf-2.0)

**Comment by moritzheiber** [comment]
Thanks!

**Comment by eriabfour** [comment]
Reminder that Dominique Lasserre aka @Lasall is a bully who is not trying to cover up how he and his bully buddies in the hate group Storm Ryders have been abusing me for years.
