### ISSUE TITLE
_comp_dpkg_installed_packages problem

### ISSUE THREAD

**Issue by osmanlicilegi** [ilikenwf/apt-fast#51]
When I try to use the command "apt-fast -y --purge autoremove" with a tab, it's gives error "_comp_dpkg_installed_packages: command not found". I've found and installed bash-completion-lib via https://code.google.com/p/bash-completion-lib/ but nothing was changed. I'm on Ubuntu 13.04 and have installed apt-fast via ppa repository.

**Comment by dawez** [comment]
I also run across this bug. It seems that the problem is due the completition file:

In my case I have it under:
/etc/bash_completion.d/apt-fast

Look at the file while it says:
# Debian system
COMPREPLY=( $( _comp_dpkg_installed_packages $cur ) )

Replace with:
# Debian system
COMPREPLY=( $( _xfunc dpkg _comp_dpkg_installed_packages "$cur" ) )

This will allow to fix the issue.

Have a look here for the full explanation of a similar bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=680663
